VenteLivre/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import path, include 
from django.conf import settings 
from django.conf.urls.static import static 


urlpatterns = [
    # NEW: path for app pages
    path('', include('pages.urls')),
    # NEW: path for account management
    path('accounts/', include('accounts.urls')), 
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'  

urlpatterns = [
    #PATH
    path('', views.home, name='home'),
    path('categories', views.categories, name='categories'),
    
    # =============Path about Auteurs====================================
    path('ajouter_auteur', views.ajouter_auteur, name = 'ajouter_auteur'),
    path('modifier_auteur/<int:id_auteur>/', views.modifier_auteur, name = 'modifier_auteur'),
    path('supprime_auteur/<int:id_auteur>/', views.supprime_auteur, name = 'supprime_auteur'),
    path('affichage_auteur', views.affichage_auteur, name ='affichage_auteur'),
    # =============Path Fin Auteurs======================================
    
    # =============Path about Comptes ==========================================
    path('compte', views.creation_compte, name = 'compte'),
    path('affichage_compte', views.affichage_compte, name ='affichage_compte'),
    path('modifier_compte/<int:id_compte>/', views.modifier_compte, name = 'modifier_compte'),
    path('supprime_compte/<int:id_compte>/', views.supprime_compte, name = 'supprime_compte'),
    # =============Path Fin Comptes ==========================================
    
    # =============Path about penses_Positives ==========================================
    path('pense_positives', views.pense_positive, name = 'pense_positives'),
    path('messageImg', views.message_image, name = 'messageImg'),
    path('affichage_penses', views.affichage_penses, name ='affichage_penses'),
    path('image_list', views.image_list, name ='image_list'),
    # =============Path Fin  penses_Positives ==========================================
    
    # =============Path about livre ==========================================
    path('mesLivres', views.mes_livres, name = 'mesLivres'),
    path('affichage_livre', views.affichage_livre, name = 'affichage_livre'),
    # =============Path fin livre ==========================================
    
   
    # =============Path about Faire un ACHAT ==========================================
    path('formulaire', views.formulaire, name='formulaire'),
    path('affichage_achat', views.affichage_achat, name = 'affichage_achat'),
    # =============Path fin Faire un ACHAT ==========================================
    
    # =============Path  telechargement PDF ========================
    # # path('telecharger_pdf/<int:livre_id>', views.telecharger_pdf, name='telecharger_pdf'),
    # path('telecharger_pdf', views.telecharger_pdf, name='telecharger_pdf'),
    
    
    #======================Emvoit message===================
    path('contact_send', views.contact_send, name='contact_send'),
    # =============Path about  A propos ==========================================
    path('about', views.about, name='about'),

    

]

base/views.py
from django.shortcuts import render

# Create your views here.

base/templates/base-template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Vente en ligne">
    <meta name="author" content="Louange Balerwa">

    <title>{% block 'title' %} {% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bases.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/stylesTab.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css"> 
</head>

<body>
  <div class="principale">
    <div class="contenaires">
      <header>
        <!-- Menu principale -->
          <ul class="menu">
            <li><a href="{% url 'pages:home'%}">Home Page</a></li>
            <li><a href="{% url 'pages:categories' %}" >Vers Page Menus</a></li>
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'pages:affichage_auteur'%}">Voir Auteurs</a></li>
            <li><a href="{% url 'pages:affichage_compte'%}">Creer un Comptes</a></li>
            <li><a href="{% url 'pages:contact_send' %}">Contact</a></li>
            <li><a href="{% url 'pages:about' %}">About Me</a></li>
          </ul>
      </header>
      {% block 'content' %}
      {% endblock %}
    </div>
    
    <div class="contenaires">
       <!-- Footer  -->
      <footer >
        <div class="footer-text">
          <!-- Realisateur -->
          <p>Réalisé par <span>louangebalerwa</span> | Tous les droits sont reservés. <br>&copy; Vente de livres 2024</p>
          </p>
        </div>
      </footer>
    </div>
      
  </div>
  
    
</body>
</html>