VenteLivre/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import path, include 
from django.conf import settings 
from django.conf.urls.static import static 


urlpatterns = [
    # NEW: path for app pages
    path('', include('pages.urls')),
    # NEW: path for account management
    path('accounts/', include('accounts.urls')), 
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'  

urlpatterns = [
    #PATH
    path('', views.home, name='home'),
    path('categories', views.categories, name='categories'),
    
    # =============Path about Auteurs====================================
    path('ajouter_auteur', views.ajouter_auteur, name = 'ajouter_auteur'),
    path('modifier_auteur/<int:id_auteur>/', views.modifier_auteur, name = 'modifier_auteur'),
    path('supprime_auteur/<int:id_auteur>/', views.supprime_auteur, name = 'supprime_auteur'),
    path('affichage_auteur', views.affichage_auteur, name ='affichage_auteur'),
    # =============Path Fin Auteurs======================================
    
    # =============Path about Comptes ==========================================
    path('compte', views.creation_compte, name = 'compte'),
    path('affichage_compte', views.affichage_compte, name ='affichage_compte'),
    path('modifier_compte/<int:id_compte>/', views.modifier_compte, name = 'modifier_compte'),
    path('supprime_compte/<int:id_compte>/', views.supprime_compte, name = 'supprime_compte'),
    # =============Path Fin Comptes ==========================================
    
    # =============Path about penses_Positives ==========================================
    path('pense_positives', views.pense_positive, name = 'pense_positives'),
    path('messageImg', views.message_image, name = 'messageImg'),
    path('affichage_penses', views.affichage_penses, name ='affichage_penses'),
    path('image_list', views.image_list, name ='image_list'),
    # =============Path Fin  penses_Positives ==========================================
    
    # =============Path about livre ==========================================
    path('mesLivres', views.mes_livres, name = 'mesLivres'),
    path('affichage_livre', views.affichage_livre, name = 'affichage_livre'),
    # =============Path fin livre ==========================================
    
   
    # =============Path about Faire un ACHAT ==========================================
    path('formulaire', views.formulaire, name='formulaire'),
    path('affichage_achat', views.affichage_achat, name = 'affichage_achat'),
    # =============Path fin Faire un ACHAT ==========================================
    
    # =============Path  telechargement PDF ========================
    # # path('telecharger_pdf/<int:livre_id>', views.telecharger_pdf, name='telecharger_pdf'),
    # path('telecharger_pdf', views.telecharger_pdf, name='telecharger_pdf'),
    
    
    #======================Emvoit message===================
    path('contact_send', views.contact_send, name='contact_send'),
    # =============Path about  A propos ==========================================
    path('about', views.about, name='about'),

    

]

pages/models.py
from django.db import models
from django.contrib.auth import get_user_model

from django.utils import timezone


# ================== classe Auteur===================================
class auteur(models.Model):
    nom_auteur = models.CharField(max_length=100, unique = True)
    email = models.EmailField()
    num_tel = models.IntegerField(default=0)
    pays = models.CharField(max_length=64, blank=True)
    ville = models.CharField(max_length=64, blank=True)
    matricule = models.IntegerField(default=0)
    
    def __str__(self):
        return self.nom_auteur
    def get_absolute_url(self):
        return "affichage_auteur"
    
# ================== classe Compte===================================
class creationCompte(models.Model):
    matricule = models.IntegerField(unique=True, default=0)
    type_compte = models.CharField(max_length=32)
    balance = models.IntegerField(default=0)
    
    def __str__(self):
        return self.type_compte
    def get_absolute_url(self):
        return "affichage_compte"

# ================== classe Livre===================================
class livre(models.Model):
    auteur = models.ForeignKey(auteur, on_delete= models.DO_NOTHING, default=1)
    Titre = models.CharField(unique=True, max_length=200)
    photo = models.ImageField(upload_to='images', blank=True )
    fichier_pdf = models.FileField(upload_to='documents_pdf', blank=True)
    prix = models.IntegerField(default=0)
    date_pub = models.DateField(default=timezone.now)
    
    
    def __str__(self):
        return self.Titre
    def get_absolute_url(self):
        return "affichage_livre"
    
# ================== classe carnet parole===================================
class pensesPositives(models.Model):
    TitreP = models.CharField(unique=True, max_length=200)
    contenus = models.TextField(blank=False)
    nom_auteur = models.CharField(max_length=100)
    date= models.DateField(default=timezone.now)
    
    def __str__(self):
        return self.TitreP
    def get_absolute_url(self):
        return "affichage_penses"
    
# ================== classe carnet Image===================================
class messageImage(models.Model):
    nom_auteur = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images', blank= False)
    date_mes = models.DateField(default=timezone.now)
    
    def __str__(self):
        return self.nom_auteur
    def get_absolute_url(self):
        return "image_list"
    
# ================== classe faire Achats=================================== 
class achat(models.Model):
    nom_livre = models.ForeignKey(livre, on_delete= models.DO_NOTHING, default=1)
    nombre_piece = models.IntegerField(default=1)
    matricule = models.ForeignKey(creationCompte, on_delete= models.DO_NOTHING, default=0)
    Nom = models.CharField(max_length=90)
    email = models.EmailField()
    telephone = models.IntegerField(default=0)
    pays = models.CharField(max_length=90, blank=True)
    date_achat = models.DateField(default=timezone.now)
    
    def __str__(self):
        return self.Nom  
    def get_absolute_url(self):
        return "affichage_achat"
    

pages/templates/pages/about.html
{% extends 'base-template.html' %}

{% load static %}

{% block 'title' %}About Me{% endblock %}

{% block 'content' %}
    <section class="about">
        <h1>About Me</h1>
        <p>
            Moi c'est LOUANGE BALERWA, j'ai devellopé ce site, <br> 
            <br>
            <br>

            avec le but de vous faciliter de faire vos Ventes et Achats de livres en ligne avec toute securite!
        </p>
        <div>
            
        </div>
        
    </section>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

pages/templates/pages/affichage_auteur.html
{% extends 'base-template.html' %}

{% load static %}

{% block 'title' %}Show_Auteur{% endblock %}

{% block 'content' %}
    <h1>Listes des Auteurs {% if perms.pages.add_auteur %}<a href ="ajouter_auteur" class="btn_save">Ajouter</a> {% endif %}</h1>
    <br>
    <table  class="tableau" >
        <thead>
            <tr>
                <th>ID</th>
                <th>NOM</th>
                <th>ADRESSE MAIL</th>
                <th>NUMERO_TEL</th>
                <th>MATRICULE</th>
                <th>PAYS</th>
                <th>VILLE</th>
                <th>ACTION</th>
            </tr>
        </thead>
        <tbody>
            {% for auteur in auteurs %}
                <tr>
                    <td>{{ auteur.id }}</td>
                    <td>{{ auteur.nom_auteur }}</td>
                    <td>{{ auteur.email}}</td>
                    <td>{{ auteur.num_tel }}</td>
                    <td>{{ auteur.matricule }}</td>
                    <td>{{ auteur.pays }}</td>
                    <td>{{ auteur.ville }}</td>
                    <td>{% if perms.pages.change_auteur %}
                        <a href="{% url 'pages:modifier_auteur' auteur.id %}" class="btn_edit">Editer</a>
                        {% endif %}
                        {% if perms.pages.delete_auteur %}
                        <a href="{% url 'pages:supprime_auteur' auteur.id %}" class="btn_supprime"> X </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="8">
                    Liste des Auteurs!!!
                </td>
            </tr>
        </tfoot>
    </table> 
<br>
<br>
<br>
<br>
<br>

 
{% endblock %}

pages/templates/pages/affichage_compte.html
{% extends 'base-template.html' %}

{% load static %}

{% block 'title' %}Show_Compte{% endblock %}

{% block 'content' %}
    <h1>Listes des Comptes<a href ="compte" class="btn_save">Ajouter</a></h1>
    <br>
    <table  class="tableau" >
        <thead>
            <tr>
                <th>ID</th>
                <th>MATRICULE</th>
                <th>TYPE DE COMPE</th>
                <th>BALANCE</th>
                <th>ACTION</th>
            </tr>
        </thead>
        <tbody>
            {% for compte in comptes %}
                <tr>
                    <td>{{ compte.id }}</td>
                    <td>{{ compte.matricule }}</td> 
                    <td>{% if perms.pages.delete_auteur %}{{ compte.type_compte }} {% endif %}</td>
                    <td>{{ compte.balance}}</td>
                    <td><a href="{% url 'pages:modifier_compte' compte.id %}" class="btn_edit">Editer</a>
                        <a href="{% url 'pages:supprime_compte' compte.id %}" class="btn_supprime"> Supprimer </a>
                    </td>              
                </tr>
            {% endfor %}
        </tbody>
        <tfoot>                        
            <tr>
                <td colspan="5">
                    Liste des Comptes!!!
                </td>
            </tr>
        </tfoot>
    </table> 
      <br>
      <br>
      <br>
      <br>
      <br>
        
{% endblock %}

pages/templates/pages/affichage_livre.html
{% extends 'base-template.html' %}

{% load static %}

{% block 'title' %}Articles{% endblock %}

{% block 'content' %}
<section class="livres">  
        {% for livre in livres%}
        <div class="livre">
            <h2>{{livre.Titre}}</h2>
          {% if livre.photo %}
            <img src = "/media/{{livre.photo}}">
          {% endif %}
          <p>Prix : {{livre.prix}} $</p>
          <p>Date de publication: {{livre.date_pub}}</p>
          <p>Auteur : {{livre.auteur}}</p>
          <a href="{{livre.fichier_pdf.url}}">Telechargement PDF</a>
        </div>
      {% endfor %}
      <div>
        <ul class="menu_livre_bt">
          <li><a href="{% url 'pages:mesLivres' %}">Publication Un livre</a></li> 
          <li><a href="{% url 'pages:formulaire'%}">Acheter</a></li>
        </ul>
      </div>  
</section>
<br>
<br>
{% endblock %}

pages/templates/pages/ajouter_auteur.html
{% extends 'base-template.html' %}

{% load static %}

{% block 'title' %}Ajout_auteur{% endblock %}

{% block 'content' %} 
  <h1>Ajouter Auteur</h1> 
  <section id="publcation">
    <form action = "{% url 'pages:ajouter_auteur' %}"  method="POST">
      {% csrf_token %}
      {{form.as_p}}

      <input type="submit" name="" value="Envoyer"> 
    
  </form>
  </section>

{% endblock %}

pages/templates/pages/compte.html
{% extends 'base-template.html' %}

{% load static %}

{% block 'title' %}Creer_compte{% endblock %}

{% block 'content' %} 
    <h1>Creation de Compte</h1> 
  <section id="">
    <form action = "{% url 'pages:compte' %}"  method="POST">
      {% csrf_token %}
      {{form.as_p}}

      <input type="submit" name="" value="Envoyer"> 
    
  </form>
  </section>

{% endblock %}

pages/templates/pages/contact_send.html
{% extends 'base-template.html' %}

{% load static %}

{% block 'title' %}Contact{% endblock %}

{% block 'content' %}
    <h1>Envoyer un message</h1>

    <form action="{% url 'pages:contact_send' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">Nom:</label>
            <input type="text" id="name" name="name" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="message">Message:</label>
            <textarea id="message" name="message" class="form-control" rows="5" required></textarea>
        </div>
        <button type="submit" class="btn">Envoyer</button>
    </form>
{% endblock %}

pages/templates/pages/image_list.html
{% extends 'base-template.html' %}

{% load static %}

{% block 'title' %}Show_Images{% endblock %}

{% block 'content' %}
    <!-- <div>
      {% for message in messages %}
         <h2>{{message.nom_auteur}}</h2>
          {% if message.image %}
            <img src = "/media/{{message.image}}" width="96" height ="96">
          {% endif %}
         <p>{{message.date_mes}}</p>
      {% endfor %}

    </div>
            
      
    <div>
      <a href="{% url 'pages:categories' %}" id = "retour">Vers Page Menus</a>
    </div> -->
    {% for article in articles %}
    <div class="pathimage">
      {% if article.image %}
        <img src = "/media/{{article.image}}" >
      {% endif %}
      <h2>Auteur: {{article.nom_auteur }}</h2>
      <p>Date: {{article.date_mes}}</p>
    </div>
    {% endfor %}

{% if paginator.num_pages > 1 %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page_lien"><a href="?page={{ page_obj.previous_page_number }}">Précédent</a></li>
        {% endif %}

        {% for page_number in paginator.page_range %}
            {% if page_number == page_obj.number %}
                <li class="active"><a href="?page={{ page_number }}">{{ page_number }}</a></li>
            {% else %}
                <li class="active_btn"><a href="?page={{ page_number }}">{{ page_number }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page_lien"><a href="?page={{ page_obj.next_page_number }}">Suivant</a></li>
        {% endif %}
    </ul>
    <div >
      <ul class="menu_livre">
        <li><a href="{% url 'pages:messageImg' %}">Publier une Photo</a></li>
      </ul>
    </div>
{% endif %}

        
{% endblock %}

pages/templates/pages/livres.html
{% extends 'base-template.html' %}

{% load static %}

{% block 'title' %}Nos Livres{% endblock %}

{% block 'content' %}
    <h1>Publier un Livre</h1>
        <form action = "{% url 'pages:mesLivres' %}"  enctype="multipart/form-data" method="POST" >
            {% csrf_token %}
            {{form.as_p}}
      
            <input type="submit" name="" value="Envoyer"> 

    </div>
{% endblock %}

pages/templates/pages/messageImg.html
{% extends 'base-template.html' %}

{% load static %}

{% block 'title' %}Puplication des Carnet{% endblock %}

{% block 'content' %} 
    <h1>Puplication un Carnet</h1> 
  <section id="">
    <form action = "{% url 'pages:messageImg' %}"  method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}

      <input type="submit" name="" value="Envoyer"> 
    <div>
      <a href="{% url 'pages:affichage_penses' %}"><input type="button" value="Retour"></a>
    </div>
    
  </form>
  

  </section>
<br>
<br>
<br>
{% endblock %}

pages/templates/pages/modifier_auteur.html
{% extends 'base-template.html' %}

{% load static %}

{% block 'title' %}Edit_auteur: {{data.nom_auteur}}{% endblock %}

{% block 'content' %} 
    <h1>Modifier un Auteur</h1> 
  <section>
    <form action = "{% url 'pages:modifier_auteur' data.id %}"  method="POST">
      {% csrf_token %}
      {{form.as_p}}

      <input type="submit" name="" value="Envoyer"> 
    
  </form>
  </section>

{% endblock %}

pages/templates/pages/modifier_compte.html
{% extends 'base-template.html' %}

{% load static %}

{% block 'title' %}Edit_Compte: {{data.matricule}}{% endblock %}

{% block 'content' %} 
    <h1>Modifier un Compte</h1> 
  <section>
    <form action = "{% url 'pages:modifier_compte' data.id %}"  method="POST">
      {% csrf_token %}
      {{form.as_p}}

      <input type="submit" name="" value="Envoyer"> 
    
  </form>
  </section>

{% endblock %}

pages/templates/pages/pense_positives.html
{% extends 'base-template.html' %}

{% load static %}

{% block 'title' %}Penses Positives{% endblock %}

{% block 'content' %}
    <h1>Puplication un Carnet</h1>
    <div class="pense">
        <form action = "{% url 'pages:pense_positives' %}"  method="POST">
            {% csrf_token %}
            {{form.as_p}}
      
            <input type="submit" name="" value="Envoyer"> 
        <div>
            <a href="{% url 'pages:affichage_penses' %}"><input type="button" value="Retour"></a>
        </div>   
    </div>
   
   
{% endblock %}

pages/templates/pages/supprime_auteur.html
{% extends 'base-template.html' %}

{% load static %}

{% block 'title' %}Supprime_Auteur: {{data.nom_auteur}}{% endblock %}

{% block 'content' %} 
    <h1>Modifier un Auteur</h1> 
  <section>
    <form action = "{% url 'pages:supprime_auteur' data.id %}"  method="POST">
      {% csrf_token %}
      <br>
      <p>Voullez-vous supprimez l'auteur {{data.nom_auteur}} ?</p>
      <br>
      <input type="submit" name="" value="Confimer"> 
      <div>
        <a href="{% url 'pages:affichage_auteur' %}"><input type="button" value="Cancel"></a>
      </div>
    
  </form>
  </section>

{% endblock %}